export const SUCCESS_FETCH_COURSES = 'SUCCESS_FETCH_COURSES';
export const FETCH_COURSES = 'FETCH_COURSES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SUCCESS_SEND_MESSAGE = 'SUCCESS_SEND_MESSAGE';
