# Generated by Django 2.0.1 on 2018-01-27 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180127_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='send_to',
        ),
        migrations.AddField(
            model_name='studentinmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_messages', to='server.Message'),
        ),
        migrations.AddField(
            model_name='studentinmessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mstudents', to='server.Student'),
        ),
    ]
