# Generated by Django 2.0.1 on 2018-01-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180127_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='completed',
            field=models.NullBooleanField(),
        ),
    ]
